- name: Create Static IP Routes
  hosts: all
  tasks:
    - block:
        - name: Create Static IP Routes | Live IP Route
          command: "ip route add {{ item }}"
          with_items: "{{ static_ip_routes }}"

        - name: Create Static IP Routes | Permanent IP Route
          lineinfile:
            path: "/etc/sysconfig/network-scripts/route-eth0"
            state: present
            create: True
            line: "{{ item }}"
          with_items: "{{ static_ip_routes }}"
      when: static_ip_routes is defined
